test

diff --git a/ci/plugins/mzcompose/hooks/post-command b/ci/plugins/mzcompose/hooks/post-command
--- a/ci/plugins/mzcompose/hooks/post-command
+++ b/ci/plugins/mzcompose/hooks/post-command
@@ -11,14 +11,6 @@
 
 set -euo pipefail
 
-ulimit -a
-
-ulimit -S -a
-
-echo "Core pattern:"
-
-cat /proc/sys/kernel/core_pattern
-
 . misc/shlib/shlib.bash
 
 run() {
@@ -78,13 +70,29 @@ netstat -panelot > netstat-panelot.log
 ps aux > ps-aux.log
 docker ps -a --no-trunc > docker-ps-a.log
 
+mv "$HOME"/cores .
+
+if find cores -name 'core.*' | grep -q .; then
+    # Best effort attempt to fetch interesting executables to get backtrace of core files
+    run cp sqllogictest:/usr/local/bin/sqllogictest cores/ || true
+    run cp sqllogictest:/usr/local/bin/clusterd cores/ || true
+    run cp materialized:/usr/local/bin/environmentd cores/ || true
+    run cp materialized:/usr/local/bin/clusterd cores/ || true
+    run cp testdrive:/usr/local/bin/testdrive cores/ || true
+fi
+
 ls -lha cores
-find cores -name 'core.*' | while read -r i; do
-    buildkite-agent artifact upload "$i"
+
+find cores -name 'core.*' | while read -r core; do
+    exe=$(echo "$core" | sed -e "s/core\.\(.*\)\.[0-9][0-9]*/\1/")
+    bin/ci-builder run nightly gdb cores/"$exe" "$core" --batch -ex bt full -ex quit > "$core".txt || true
+    buildkite-agent artifact upload "$core".txt
+    buildkite-agent artifact upload "$core"
 done
+# can be huge, clean up
 rm -rf cores
 
-artifacts=(run.log services.log journalctl-merge.log netstat-ant.log netstat-panelot.log ps-aux.log docker-ps-a.log docker-inspect.log sar.log)
+artifacts=(run.log services.log journalctl-merge.log netstat-ant.log netstat-panelot.log ps-aux.log docker-ps-a.log docker-inspect.log)
 artifacts_str=$(IFS=";"; echo "${artifacts[*]}")
 buildkite-agent artifact upload "$artifacts_str"
 bin/ci-builder run stable bin/ci-logged-errors-detect "${artifacts[@]}"
